# ObsidianGate spawn protection. Covers the castle spawn and 200-block roads.
enabled=true
radius=40
centerMode=worldspawn
dimension=0
centerX=484.0
centerZ=-823.0
protectBlocks=true
denyHostileSpawns=true
denyExplosions=true
allowOperatorBypass=false
regionMode=box
minX=284.0
minY=0.0
minZ=-1023.0
maxX=684.0
maxY=255.0
maxZ=-623.0
